//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameInput
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""48baa110-f276-402f-9d39-a10d4a778f53"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""30b162b5-b558-4fc3-aebc-87e29ba0ec27"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PreviousItem"",
                    ""type"": ""Button"",
                    ""id"": ""36e2d43d-ced5-43bd-be0f-52d51aea5ff6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextItem"",
                    ""type"": ""Button"",
                    ""id"": ""ca4d5dd0-a9e1-4988-9959-7182d78f2f2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowItem"",
                    ""type"": ""Button"",
                    ""id"": ""653f0998-3bb9-4743-9b74-e90ef536c4eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PerformAction"",
                    ""type"": ""Button"",
                    ""id"": ""44e4f964-4cc7-436e-b9f8-93b8517ba5ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""f9f5e227-6bc3-468b-a133-bc62d4be857d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CancelAction"",
                    ""type"": ""Button"",
                    ""id"": ""f28f0e1c-b310-4b2a-989d-7ab64f7899f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""9e1ef794-daa3-4a2f-9370-8aab07c7c7f7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""34ed8b97-43a0-466e-90db-c68f0ba80d59"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fbd008f6-69ea-44c1-935e-acd316dd0555"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2a139920-8663-466f-a13b-7ef577e6de27"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7f77ddb1-2f67-4566-b2dd-43ab56d32e17"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3161c33d-e38c-4252-aef4-17eedcb1d1bf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6357395-e1bb-4b56-b05d-cae0f5c2ed92"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6db407b-f50d-4f87-9b7f-f76a4980449c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ebe1b60-3e39-4c87-83c1-ba2ef0358366"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PerformAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3615de1-7439-41fc-838b-7704de02cd28"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f2d383a-dcd5-4dab-b88d-f28f66132490"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Game
            m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
            m_Game_Walk = m_Game.FindAction("Walk", throwIfNotFound: true);
            m_Game_PreviousItem = m_Game.FindAction("PreviousItem", throwIfNotFound: true);
            m_Game_NextItem = m_Game.FindAction("NextItem", throwIfNotFound: true);
            m_Game_ThrowItem = m_Game.FindAction("ThrowItem", throwIfNotFound: true);
            m_Game_PerformAction = m_Game.FindAction("PerformAction", throwIfNotFound: true);
            m_Game_MousePosition = m_Game.FindAction("MousePosition", throwIfNotFound: true);
            m_Game_CancelAction = m_Game.FindAction("CancelAction", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Game
        private readonly InputActionMap m_Game;
        private IGameActions m_GameActionsCallbackInterface;
        private readonly InputAction m_Game_Walk;
        private readonly InputAction m_Game_PreviousItem;
        private readonly InputAction m_Game_NextItem;
        private readonly InputAction m_Game_ThrowItem;
        private readonly InputAction m_Game_PerformAction;
        private readonly InputAction m_Game_MousePosition;
        private readonly InputAction m_Game_CancelAction;
        public struct GameActions
        {
            private @InputActions m_Wrapper;
            public GameActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Walk => m_Wrapper.m_Game_Walk;
            public InputAction @PreviousItem => m_Wrapper.m_Game_PreviousItem;
            public InputAction @NextItem => m_Wrapper.m_Game_NextItem;
            public InputAction @ThrowItem => m_Wrapper.m_Game_ThrowItem;
            public InputAction @PerformAction => m_Wrapper.m_Game_PerformAction;
            public InputAction @MousePosition => m_Wrapper.m_Game_MousePosition;
            public InputAction @CancelAction => m_Wrapper.m_Game_CancelAction;
            public InputActionMap Get() { return m_Wrapper.m_Game; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
            public void SetCallbacks(IGameActions instance)
            {
                if (m_Wrapper.m_GameActionsCallbackInterface != null)
                {
                    @Walk.started -= m_Wrapper.m_GameActionsCallbackInterface.OnWalk;
                    @Walk.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnWalk;
                    @Walk.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnWalk;
                    @PreviousItem.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPreviousItem;
                    @PreviousItem.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPreviousItem;
                    @PreviousItem.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPreviousItem;
                    @NextItem.started -= m_Wrapper.m_GameActionsCallbackInterface.OnNextItem;
                    @NextItem.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnNextItem;
                    @NextItem.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnNextItem;
                    @ThrowItem.started -= m_Wrapper.m_GameActionsCallbackInterface.OnThrowItem;
                    @ThrowItem.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnThrowItem;
                    @ThrowItem.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnThrowItem;
                    @PerformAction.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPerformAction;
                    @PerformAction.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPerformAction;
                    @PerformAction.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPerformAction;
                    @MousePosition.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                    @MousePosition.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                    @MousePosition.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                    @CancelAction.started -= m_Wrapper.m_GameActionsCallbackInterface.OnCancelAction;
                    @CancelAction.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnCancelAction;
                    @CancelAction.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnCancelAction;
                }
                m_Wrapper.m_GameActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Walk.started += instance.OnWalk;
                    @Walk.performed += instance.OnWalk;
                    @Walk.canceled += instance.OnWalk;
                    @PreviousItem.started += instance.OnPreviousItem;
                    @PreviousItem.performed += instance.OnPreviousItem;
                    @PreviousItem.canceled += instance.OnPreviousItem;
                    @NextItem.started += instance.OnNextItem;
                    @NextItem.performed += instance.OnNextItem;
                    @NextItem.canceled += instance.OnNextItem;
                    @ThrowItem.started += instance.OnThrowItem;
                    @ThrowItem.performed += instance.OnThrowItem;
                    @ThrowItem.canceled += instance.OnThrowItem;
                    @PerformAction.started += instance.OnPerformAction;
                    @PerformAction.performed += instance.OnPerformAction;
                    @PerformAction.canceled += instance.OnPerformAction;
                    @MousePosition.started += instance.OnMousePosition;
                    @MousePosition.performed += instance.OnMousePosition;
                    @MousePosition.canceled += instance.OnMousePosition;
                    @CancelAction.started += instance.OnCancelAction;
                    @CancelAction.performed += instance.OnCancelAction;
                    @CancelAction.canceled += instance.OnCancelAction;
                }
            }
        }
        public GameActions @Game => new GameActions(this);
        public interface IGameActions
        {
            void OnWalk(InputAction.CallbackContext context);
            void OnPreviousItem(InputAction.CallbackContext context);
            void OnNextItem(InputAction.CallbackContext context);
            void OnThrowItem(InputAction.CallbackContext context);
            void OnPerformAction(InputAction.CallbackContext context);
            void OnMousePosition(InputAction.CallbackContext context);
            void OnCancelAction(InputAction.CallbackContext context);
        }
    }
}
